### ISSUE TITLE
Please add example for J305 tube

### ISSUE THREAD

**Issue by alexeyzel** [iotdevicesdev/GGreg20_V3-ESP32-HomeAssistant-ESPHome#1]
Please add an example for J305 tube.
In example, I found for other board with j305 tube there is "offset: -12.0" filter because J305 has background noise 0.2 pulses / sec x 60 sec = 12 CPM (Counts per minute), should I use this filter?

**Comment by iotdevicesdev** [comment]
Thank you for your question. You are correct. If you have a J305 tube, the documentation for the tube indicates that the internal noise of the tube is 0.2 pulses per second. That is, these are pulses that occur in the complete absence of external radiation. Thus, this is the number of false-positive pulses that should be filtered out. Within the measurement period, i.e. 60 seconds, you need to discard 0.2 * 60 = 12 pulses per minute.
Please also note that for some reason, it is not common for SBM20 tubes to filter out false-positive pulses, although the tube documentation indicates that SBM20 tubes will have 1 such pulse per second. This value is much higher than that of the J305, which, frankly, makes the SBM20 tube not very suitable for measuring background radiation in normal conditions. However, SBM20 is very popular and we see it in our statistics as well. However, we recommend choosing J305 for our part. We even wrote an article about it.
https://iot-devices.com.ua/en/comparison-of-geiger-muller-tubes-sbm20-j305-and-lnd712/

As for individual examples for different tubes, of course, we plan to post them as well asap.

Best Regards,
Oleksii
Team IoT-devices, LLC
